name: Docker Build and Push

on:
  push:
    branches:
      - Estimation-github-Raghunath9493-200130

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.raghunath01 }}
          DOCKER_PASSWORD: ${{ secrets.Kunidoc@1998 }}
          IMAGE_NAME: Raghunath9493/materialdonar-app-1
          TAG: latest
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:$TAG . --push
