name: Docker Build and Push

on:
  push:
    branches:
      - Estimation-github-Raghunath9493-200130

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker --version

      - name: Build Docker image
        run: |
          cd crew_manual
          docker build -t Raghunath9493/materialdonar-app-1 .

      - name: Log in to Docker Hub
        run: docker login -u kunigiriraghunath9493@gmail.com -p Kunidoc@1998

      - name: Push Docker image
        run: docker push raghunathk01/materialdonar-app-1

      - name: Deploy Docker container
        run: docker run -p 8080:8080 raghunath01/materialdonar-app-1
